import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SearchBox from '../components/SearchBox';
import Nav from '../components/Nav';

const Home: NextPage = () => {
  return (
    <>
    <Nav />
    <div className={styles.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          Hello World!
        </h1>
        <SearchBox />
      </main>
      
    </div>
    </>
  );
};

export default Home;
